name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping request to Streamlit app
        run: |
          # Removed "-L" (don't follow redirects) and added embed parameters
          curl -s -w "%{http_code}" "https://jemkbdnsnauaqjx5c75tx5.streamlit.app/" -o /dev/null
          
